import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
public object Libs {
    public const val activity_compose: String = "androidx.activity:activity-compose:_"

    public const val appcompat: String = "androidx.appcompat:appcompat:_"

    public const val androidx_compose_compiler_compiler: String =
            "androidx.compose.compiler:compiler:_"

    public const val material3: String = "androidx.compose.material3:material3"

    public const val ui: String = "androidx.compose.ui:ui"

    public const val ui_graphics: String = "androidx.compose.ui:ui-graphics"

    public const val ui_test_junit4: String = "androidx.compose.ui:ui-test-junit4"

    public const val ui_test_manifest: String = "androidx.compose.ui:ui-test-manifest"

    public const val ui_tooling: String = "androidx.compose.ui:ui-tooling"

    public const val ui_tooling_preview: String = "androidx.compose.ui:ui-tooling-preview"

    public const val compose_bom: String = "androidx.compose:compose-bom:_"

    public const val core_ktx: String = "androidx.core:core-ktx:_"

    public const val lifecycle_runtime_ktx: String = "androidx.lifecycle:lifecycle-runtime-ktx:_"

    public const val espresso_core: String = "androidx.test.espresso:espresso-core:_"

    public const val androidx_test_ext_junit: String = "androidx.test.ext:junit:_"

    public const val com_android_application_gradle_plugin: String =
            "com.android.application:com.android.application.gradle.plugin:_"

    public const val com_android_library_gradle_plugin: String =
            "com.android.library:com.android.library.gradle.plugin:_"

    public const val material: String = "com.google.android.material:material:_"

    public const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    public const val junit_junit: String = "junit:junit:_"

    public const val org_jetbrains_kotlin_android_gradle_plugin: String =
            "org.jetbrains.kotlin.android:org.jetbrains.kotlin.android.gradle.plugin:_"
}
